import os
import sys
import subprocess
import getpass

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def prompt_input(prompt_text, default=None, required=True, secret=False):
    while True:
        default_str = f" [{default}]" if default is not None else ""
        full_prompt = f"{prompt_text}{default_str}: "
        
        if secret:
            val = getpass.getpass(full_prompt).strip()
        else:
            val = input(full_prompt).strip()
            
        if not val and default is not None:
            return default
        if not val and required:
            print("  ❌ This value is required. Please try again.")
            continue
        return val

def main():
    clear_screen()
    print("======================================================")
    print("  🚀 Market Volatility & News Bot - Interactive Setup  ")
    print("======================================================\n")

    # 1. Telegram API Credentials
    print("--- 1. Telegram API Configuration ---")
    print("Get your API credentials from: https://my.telegram.org")
    api_id = prompt_input("Enter Telegram API ID", required=True)
    api_hash = prompt_input("Enter Telegram API Hash", required=True)
    target_channel = prompt_input("Enter Target Channel (@username or ID)", required=True)
    if not target_channel.startswith("@") and not target_channel.startswith("-100"):
        target_channel = "@" + target_channel

    # 2. Volatility Thresholds
    print("\n--- 2. Market Alert Thresholds ---")
    crypto_thresh = prompt_input("Crypto 24h volatility trigger % (e.g. 5.0)", default="5.0")
    metals_thresh = prompt_input("Gold/Silver 24h volatility trigger % (e.g. 2.0)", default="2.0")
    cooldown_hours = prompt_input("Cooldown window per asset in hours (e.g. 4)", default="4")

    # 3. AI Engine Configuration
    print("\n--- 3. AI Analysis Engine ---")
    print("Select an AI provider for news root-cause analysis:")
    print(" [1] Free Tier Keyless Fallback (No API key needed)")
    print(" [2] DeepSeek API (Recommended)")
    print(" [3] OpenAI / Groq / Custom OpenAI-compatible API")
    
    ai_choice = prompt_input("Select an option [1-3]", default="1")
    
    custom_api_key = ""
    custom_api_base_url = "https://api.deepseek.com/v1"
    custom_api_model = "deepseek-chat"

    if ai_choice == "2":
        custom_api_key = prompt_input("Enter DeepSeek API Key", required=True)
        custom_api_base_url = "https://api.deepseek.com/v1"
        custom_api_model = "deepseek-chat"
    elif ai_choice == "3":
        custom_api_key = prompt_input("Enter API Key", required=True)
        custom_api_base_url = prompt_input("Enter API Base URL", default="https://api.openai.com/v1")
        custom_api_model = prompt_input("Enter Model Name (e.g. gpt-4o-mini, llama-3.3-70b-versatile)", default="gpt-4o-mini")

    # 4. Write .env File
    print("\n--- 4. Writing Configuration ---")
    env_content = f"""# Auto-generated by setup.py
TELEGRAM_API_ID={api_id}
TELEGRAM_API_HASH={api_hash}
TARGET_CHANNEL={target_channel}

CRYPTO_THRESHOLD_PCT={crypto_thresh}
METALS_THRESHOLD_PCT={metals_thresh}
COOLDOWN_HOURS={cooldown_hours}

CUSTOM_API_KEY={custom_api_key}
CUSTOM_API_BASE_URL={custom_api_base_url}
CUSTOM_API_MODEL={custom_api_model}
"""
    with open(".env", "w", encoding="utf-8") as f:
        f.write(env_content)
    print("✅ Successfully generated .env file.")

    # 5. Telegram Session Authentication
    print("\n--- 5. Telegram Authentication ---")
    print("Logging into Telegram to generate your session file...")
    try:
        from telethon.sync import TelegramClient
        client = TelegramClient('market_session', int(api_id), api_hash)
        client.start()
        client.disconnect()
        print("✅ Telegram session created successfully (market_session.session).")
    except Exception as e:
        print(f"❌ Telegram authentication error: {e}")
        print("You can run 'python bot.py' manually later to log in.")

    # 6. Systemd Background Service Generation (Linux Only)
    if sys.platform.startswith("linux"):
        print("\n--- 6. Linux systemd Service ---")
        install_service = prompt_input("Do you want to configure a systemd background service? (y/n)", default="y")
        if install_service.lower() == 'y':
            current_user = getpass.getuser()
            current_dir = os.path.abspath(os.getcwd())
            python_path = sys.executable

            service_content = f"""[Unit]
Description=Market Volatility & Macro News Telegram Bot
After=network.target

[Service]
Type=simple
User={current_user}
WorkingDirectory={current_dir}
ExecStart={python_path} bot.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
"""
            service_path = "/tmp/marketbot.service"
            with open(service_path, "w") as f:
                f.write(service_content)

            print("\nTo activate the systemd service, run:")
            print(f"  sudo cp {service_path} /etc/systemd/system/marketbot.service")
            print("  sudo systemctl daemon-reload")
            print("  sudo systemctl enable --now marketbot")

    print("\n======================================================")
    print("  🎉 Setup Complete! You can run the bot with:         ")
    print("      python bot.py                                   ")
    print("======================================================\n")

if __name__ == "__main__":
    main()
